[6.0] feature: use laravel's forceIndex implementation
colopl/laravel-spanner pull request #114
Opened 2023-06-20 06:35 UTC by taka-oyama

Fix: #112 

## Checklist

- [x] CHANGELOG

2023-06-20 09:08 UTC, zeriyoshi commented on tests/Query/BuilderTest.php
> +            ->useIndex('test_index_name2')
```suggestion
            ->ignoreIndex('test_index_name2')
```

2023-06-20 09:17 UTC, zeriyoshi requested changes
Please check suggestion

2023-06-20 09:57 UTC, zeriyoshi approved these changes
LGTM

2023-06-21 00:21 UTC, t-matsuno-777 commented on CHANGELOG.md
> +- [Breaking] Match `Quer\Builder::forceIndex()` behavior with laravel's (`forceIndex` property no longer exists). (#114)
```suggestion
- [Breaking] Match `Query\Builder::forceIndex()` behavior with laravel's (`forceIndex` property no longer exists). (#114)
```

2023-06-21 01:10 UTC, t-matsuno-777 approved these changes

2023-06-21 02:28 UTC, merged