feat: allow spanner_emulator.disable_query_null_filtered_index_check to be set
colopl/laravel-spanner pull request #180
Opened 2024-02-15 06:05 UTC by taka-oyama

An [error is thrown](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/blob/123682157cbf8fa5cb13f0d7edb9b66070bb4a11/common/errors.cc#L2539-L2554) when the following condition is met.

- Spanner Emulator is used
- index is defined as `NULL_FILTERED`
- FORCE_INDEX statement hint is set on the query

This allows it to be bypassed by calling `Builder::disableEmulatorNullFilterIndexCheck()`.

2024-02-15 09:40 UTC, tyabu12 requested changes

2024-02-15 09:40 UTC, tyabu12 commented on src/Query/Builder.php
> +    public function disableEmulatorNullFilterIndexCheck(): static
```suggestion
    /**
     * @return $this
     */
    public function disableEmulatorNullFilterIndexCheck(): static
```

2024-02-16 01:18 UTC, yamadashy commented on src/Query/Builder.php
> +    public function disableEmulatorNullFilterIndexCheck(): static
細かいのですが、 disableEmulatorNullFilter **ed** IndexCheck() にしていないのは意図されていますでしょうか？

2024-02-16 01:32 UTC, taka-oyama commented on src/Query/Builder.php
> +    public function disableEmulatorNullFilterIndexCheck(): static
fixed

2024-02-16 01:55 UTC, yamadashy commented on src/Query/Builder.php
> +use Override;
```suggestion
```
使ってなさそうです。

2024-02-16 02:14 UTC, yamadashy approved these changes

2024-02-16 02:20 UTC, tyabu12 approved these changes
LGTM

2024-02-16 02:21 UTC, merged