fix: session clear was not working correctly on CLI sessions
colopl/laravel-spanner pull request #66
Opened 2023-01-11 08:03 UTC by taka-oyama

A better implementation of https://github.com/colopl/laravel-spanner/pull/46.

Has no beaking change so it can be applied to v4.

2023-01-11 08:06 UTC, taka-oyama commented on src/Session/DeleteOperation.php
> +            $promise->wait(false);
Disable unwrapping of rejected promises so it doesn't stop the code.

2023-01-11 08:17 UTC, tyabu12 requested changes

2023-01-11 08:17 UTC, tyabu12 commented on phpstan.neon
> +        - message: "#.*#"
How about using excludePaths.analyse ?

https://phpstan.org/user-guide/ignoring-errors#excluding-whole-files

2023-01-11 08:17 UTC, tyabu12 commented on CHANGELOG.md
> +- Default SessionPool was changed from `Google\Cloud\Spanner\Session\CacheSessionPool` to `Colopl\Spanner\Session\CacheSessionPool` to patch an [unresolved issue on google's end](https://github.com/
it seems that the issue link is broken.

2023-01-11 08:38 UTC, halnique reviewed
Does it not apply to the master branch?

2023-01-11 08:38 UTC, halnique commented on src/Session/DeleteOperation.php
> + * Copyright 2016 Google Inc.
Is this correct?

2023-01-11 09:40 UTC, taka-oyama commented on phpstan.neon
> +        - message: "#.*#"
Looks good, they have been added.

2023-01-11 09:47 UTC, taka-oyama commented on src/Session/DeleteOperation.php
> + * Copyright 2016 Google Inc.
fixed.

2023-01-11 10:40 UTC, halnique approved these changes
LGTM

It would be a good idea to change the master branch (version 5.0 or later) to this approach as well.
Will this be changed in another PR?

2023-01-12 00:44 UTC, taka-oyama commented
Yes, that's the plan. I think I will just remove the old fix from v5 branch.

2023-01-12 01:00 UTC, merged