feature: Close connection after each job
colopl/laravel-spanner pull request #80
Opened 2023-02-28 02:25 UTC by taka-oyama

2023-02-28 05:07 UTC, zeriyoshi commented on src/SpannerServiceProvider.php
> +            $queue->after(static function () {
```suggestion
        $this->app->resolving('queue', function (QueueManager $queue): void {
            $queue->after(static function (): void {
```

2023-02-28 05:08 UTC, zeriyoshi requested changes
Please check suggestion

2023-03-10 04:03 UTC, halnique commented on tests/Queue/QueueEventTest.php
> +use Symfony\Component\Cache\Adapter\ArrayAdapter;
Please optimize imports.

2023-03-10 05:00 UTC, taka-oyama commented on tests/Queue/QueueEventTest.php
> +use Symfony\Component\Cache\Adapter\ArrayAdapter;
optmized.

2023-03-10 06:03 UTC, zeriyoshi approved these changes

2023-03-10 06:03 UTC, zeriyoshi commented
LGTM

2023-03-10 06:47 UTC, halnique approved these changes

2023-03-16 01:50 UTC, merged